apiVersion: v1
kind: ServiceAccount
metadata:
  name: accounts-readonly
  namespace: accounts
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: pod-reader
  namespace: accounts
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: accounts-readonly-binding
  namespace: accounts
subjects:
  - kind: ServiceAccount
    name: accounts-readonly
    namespace: accounts
roleRef:
  kind: Role
  name: pod-reader
  apiGroup: rbac.authorization.k8s.io